// Code generated by hertz generator.

package qwen

import (
	"context"

	qwen "ai_helper/biz/model/module/qwen"
	"ai_helper/biz/service"
	"ai_helper/package/log"
	"ai_helper/package/util"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// SubmitQwenTask .
// @router api/v1/qwen/submit [POST]
func SubmitQwenTask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req qwen.QwenApiRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	log.Info("/api/v1/qwen/submit request: %v", util.JsonFmt(&req))
	resp := service.SubmitQwenTask(ctx, &req)

	log.Info("/api/v1/qwen/submit response: %v", util.JsonFmt(resp))
	c.JSON(consts.StatusOK, resp)
}

// QueryQwenTaskResult .
// @router api/v1/qwen/result [GET]
func QueryQwenTaskResult(ctx context.Context, c *app.RequestContext) {
	var err error
	var req qwen.QwenApiRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	log.Info("/api/v1/qwen/result request: %v", util.JsonFmt(&req))
	resp := service.QueryQwenTaskResult(ctx, &req)

	log.Info("/api/v1/qwen/result response: %v", util.JsonFmt(resp))
	c.JSON(consts.StatusOK, resp)
}
