// Code generated by hertz generator.

package qwen

import (
	"context"

	qwen "ai_helper/biz/model/module/qwen"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// SubmitQwenTask .
// @router api/v1/qwen/submit [POST]
func SubmitQwenTask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req qwen.QwenApiRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(qwen.QwenApiResponse)

	c.JSON(consts.StatusOK, resp)
}

// QueryQwenTask .
// @router api/v1/qwen/result [GET]
func QueryQwenTask(ctx context.Context, c *app.RequestContext) {
	var err error
	var req qwen.QwenApiRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(qwen.QwenApiResponse)

	c.JSON(consts.StatusOK, resp)
}
