version: '3.8'

services:
  mysql:
    image: mysql:8.3
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql-root-key
      MYSQL_DATABASE: ai_helper
    ports:
      - "3306:3306"
    restart: unless-stopped

  minio:
    image: minio/minio:RELEASE.2024-05-28T17-19-04Z
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: minio-admin-key
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    restart: unless-stopped

  service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    depends_on:
      - mysql
      - minio
    environment:
      MYSQL_HOST: mysql
      MYSQL_DB: ai_helper
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: minio-admin-key
    restart: unless-stopped

volumes:
  mysql_data:
  minio_data: