// Code generated by hertz generator.

package qwen

import (
	"github.com/cloudwego/hertz/pkg/app"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _apiMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _v1Mw() []app.HandlerFunc {
	// your code...
	return nil
}

func _qwenMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _queryqwentaskMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _submitqwentaskMw() []app.HandlerFunc {
	// your code...
	return nil
}
