// Code generated by hertz generator.

package user

import (
	"context"

	user "ai_helper/biz/model/basic/user"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// RegisterUser .
// @router api/v1/user/register [POST]
func RegisterUser(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserApiRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.UserApiResponse)

	c.JSON(consts.StatusOK, resp)
}

// BindQwenApiKey .
// @router api/v1/user/bind [POST]
func BindQwenApiKey(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.UserApiRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(user.UserApiResponse)

	c.JSON(consts.StatusOK, resp)
}
