// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	qwen "ai_helper/biz/router/qwen"
	user "ai_helper/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	qwen.Register(r)

	user.Register(r)

}
